import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import ChildLayout from "@/components/layout";
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
    <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />

    </head>
      <body className={inter.className}>
      <ConfigProvider>
          <ChildLayout>{children}</ChildLayout>
        </ConfigProvider>
      </body>
    </html>
  );
}
